version: '3'
services:

  alpine:
    build:
      context: ./alpine
      args:
        # OPENSSL_BRANCH: master
        NGINX_VERSION: ${NGINX_VERSION:-1.13.11}
        ALPINE_URL: mirrors.ustc.edu.cn # dl-cdn.alpinelinux.org
        OPENSSL_URL: https://gitee.com/mirrors/openssl.git
    image: khs1994/nginx:${NGINX_VERSION:-1.13.11}-tls1.3-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./app:/app/test:rw

  stretch:
    build:
      context: ./stretch
      args:
        # OPENSSL_BRANCH: master
        NGINX_VERSION: ${NGINX_VERSION:-1.13.11}
        OPENSSL_URL: https://gitee.com/mirrors/openssl.git
        DEB_URL: mirrors.ustc.edu.cn # deb.debian.org
        DEB_SECURITY_URL: mirrors.ustc.edu.cn/debian-security/ # security.debian.org
    image: khs1994/nginx:${NGINX_VERSION:-1.13.11}-tls1.3-stretch
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./app:/app/test:rw
