version: '3'
services:

  alpine:
    build:
      context: ./alpine
      args:
        # OPENSSL_BRANCH: master
        OPENSSL_URL: https://gitee.com/mirrors/openssl.git
    image: khs1994/nginx:${NGINX_VERSION}-tls1.3-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./app:/app/test:rw

  stretch:
    build:
      context: ./stretch
      args:
        # OPENSSL_BRANCH: master
        OPENSSL_URL: https://gitee.com/mirrors/openssl.git
    image: khs1994/nginx:${NGINX_VERSION}-tls1.3-stretch
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./app:/app/test:rw
